// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/cordova-ionic/cordova-ionic.d.ts
interface CordovaPlugins {
  Keyboard:Ionic.Keyboard;
}
